name: Build and Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Patch Gradle Repositories
        run: |
          sed -i '/https:\/\/maven.aliyun.com\/repository\/public/d' repositories
          grep -q '^https:\/\/repo1.maven.org\/maven2$' repositories || echo 'https://repo1.maven.org/maven2' >> repositories

      - name: Build and test
        run: ./gradlew --no-daemon test shadowJar

      - name: Upload JAR artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: MultiLogin-build-artifacts
          path: |
            **/build/libs/*.jar
